# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rCenSlice.ui'
#
# Created: Thu Oct 10 13:39:34 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReCenter_Slice(object):
    def setupUi(self, ReCenter_Slice):
        ReCenter_Slice.setObjectName(_fromUtf8("ReCenter_Slice"))
        ReCenter_Slice.resize(657, 925)
        self.Horizontal = QtGui.QWidget(ReCenter_Slice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Horizontal.sizePolicy().hasHeightForWidth())
        self.Horizontal.setSizePolicy(sizePolicy)
        self.Horizontal.setObjectName(_fromUtf8("Horizontal"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Horizontal)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = MplWidget(self.Horizontal)
        self.widget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(1600, 1200))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        ReCenter_Slice.setCentralWidget(self.Horizontal)
        self.menubar = QtGui.QMenuBar(ReCenter_Slice)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ReCenter_Slice.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ReCenter_Slice)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ReCenter_Slice.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(ReCenter_Slice)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        ReCenter_Slice.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtGui.QDockWidget(ReCenter_Slice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(300, 865))
        self.dockWidget.setFloating(False)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 10, 293, 831))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget_6 = QtGui.QWidget(self.frame)
        self.layoutWidget_6.setGeometry(QtCore.QRect(120, 10, 102, 58))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget_6)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(self.layoutWidget_6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.set_margin = QtGui.QSpinBox(self.layoutWidget_6)
        self.set_margin.setMinimum(1)
        self.set_margin.setMaximum(100)
        self.set_margin.setSingleStep(1)
        self.set_margin.setProperty("value", 10)
        self.set_margin.setObjectName(_fromUtf8("set_margin"))
        self.gridLayout_3.addWidget(self.set_margin, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget_6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.sobelAxis = QtGui.QSpinBox(self.layoutWidget_6)
        self.sobelAxis.setMinimum(0)
        self.sobelAxis.setMaximum(1)
        self.sobelAxis.setSingleStep(1)
        self.sobelAxis.setProperty("value", 1)
        self.sobelAxis.setObjectName(_fromUtf8("sobelAxis"))
        self.gridLayout_3.addWidget(self.sobelAxis, 1, 1, 1, 1)
        self.layoutWidget_7 = QtGui.QWidget(self.frame)
        self.layoutWidget_7.setGeometry(QtCore.QRect(30, 80, 199, 74))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget_7)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_11 = QtGui.QLabel(self.layoutWidget_7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.viewCH_comboBox = QtGui.QComboBox(self.layoutWidget_7)
        self.viewCH_comboBox.setEditable(False)
        self.viewCH_comboBox.setObjectName(_fromUtf8("viewCH_comboBox"))
        self.gridLayout_4.addWidget(self.viewCH_comboBox, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget_7)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.referenceCH = QtGui.QComboBox(self.layoutWidget_7)
        self.referenceCH.setEditable(False)
        self.referenceCH.setObjectName(_fromUtf8("referenceCH"))
        self.gridLayout_4.addWidget(self.referenceCH, 1, 1, 1, 1)
        self.layoutWidget_8 = QtGui.QWidget(self.frame)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 170, 261, 94))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_13 = QtGui.QLabel(self.layoutWidget_8)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_7.addWidget(self.label_13)
        self.SliceName = QtGui.QLineEdit(self.layoutWidget_8)
        self.SliceName.setObjectName(_fromUtf8("SliceName"))
        self.verticalLayout_7.addWidget(self.SliceName)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_14 = QtGui.QLabel(self.layoutWidget_8)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_8.addWidget(self.label_14)
        self.ParentName = QtGui.QLabel(self.layoutWidget_8)
        self.ParentName.setObjectName(_fromUtf8("ParentName"))
        self.verticalLayout_8.addWidget(self.ParentName)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.ColorMap = QtGui.QComboBox(self.frame)
        self.ColorMap.setGeometry(QtCore.QRect(10, 300, 91, 25))
        self.ColorMap.setObjectName(_fromUtf8("ColorMap"))
        self.rColorMap = QtGui.QCheckBox(self.frame)
        self.rColorMap.setGeometry(QtCore.QRect(120, 300, 91, 21))
        self.rColorMap.setObjectName(_fromUtf8("rColorMap"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 280, 58, 15))
        self.label.setObjectName(_fromUtf8("label"))
        self.colorbar = QtGui.QCheckBox(self.frame)
        self.colorbar.setGeometry(QtCore.QRect(200, 300, 91, 21))
        self.colorbar.setObjectName(_fromUtf8("colorbar"))
        self.layoutWidget = QtGui.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 490, 186, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.addSlice = QtGui.QPushButton(self.layoutWidget)
        self.addSlice.setObjectName(_fromUtf8("addSlice"))
        self.horizontalLayout_2.addWidget(self.addSlice)
        self.saveSlice = QtGui.QPushButton(self.layoutWidget)
        self.saveSlice.setObjectName(_fromUtf8("saveSlice"))
        self.horizontalLayout_2.addWidget(self.saveSlice)
        self.Filter = QtGui.QCheckBox(self.frame)
        self.Filter.setGeometry(QtCore.QRect(10, 330, 61, 21))
        self.Filter.setObjectName(_fromUtf8("Filter"))
        self.filterBox = QtGui.QSpinBox(self.frame)
        self.filterBox.setGeometry(QtCore.QRect(80, 330, 52, 25))
        self.filterBox.setMinimum(1)
        self.filterBox.setObjectName(_fromUtf8("filterBox"))
        self.dockWidget.setWidget(self.dockWidgetContents)
        ReCenter_Slice.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(ReCenter_Slice)
        self.viewCH_comboBox.setCurrentIndex(-1)
        self.referenceCH.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ReCenter_Slice)

    def retranslateUi(self, ReCenter_Slice):
        ReCenter_Slice.setWindowTitle(_translate("ReCenter_Slice", "ReCenter Slice", None))
        self.toolBar.setWindowTitle(_translate("ReCenter_Slice", "toolBar", None))
        self.label_9.setText(_translate("ReCenter_Slice", "Margin", None))
        self.label_10.setText(_translate("ReCenter_Slice", "Axis", None))
        self.label_11.setText(_translate("ReCenter_Slice", "View channel", None))
        self.label_12.setText(_translate("ReCenter_Slice", "Reference channel", None))
        self.label_13.setText(_translate("ReCenter_Slice", "Slice Name", None))
        self.SliceName.setText(_translate("ReCenter_Slice", "None", None))
        self.label_14.setText(_translate("ReCenter_Slice", "Parent:", None))
        self.ParentName.setText(_translate("ReCenter_Slice", "TextLabel", None))
        self.rColorMap.setText(_translate("ReCenter_Slice", "reverse", None))
        self.label.setText(_translate("ReCenter_Slice", "colormap", None))
        self.colorbar.setText(_translate("ReCenter_Slice", "colorbar", None))
        self.addSlice.setText(_translate("ReCenter_Slice", "Add to Scan", None))
        self.saveSlice.setText(_translate("ReCenter_Slice", "Save to file", None))
        self.Filter.setText(_translate("ReCenter_Slice", "filter", None))

from mplwidget import MplWidget
